export const formTypes = [
  { id: "empresas", label: "Empresas" },
  { id: "usuarios", label: "Usuários" },
  { id: "pessoas", label: "Pessoas" },
  { id: "animais", label: "Animais" },
];

export const searchTypes = [
  { id: "empresas", label: "Empresas" },
  { id: "usuarios", label: "Usuários" },
  { id: "animais", label: "Animais" },
  { id: "agendamentos", label: "Agendamentos" },
  { id: "interessados", label: "Interessados" },
  { id: "tutores", label: "Tutores" },
  { id: "colaboradores", label: "Colaboradores" },
];

export const formFieldsConfig = {
  empresas: [
    {
      id: "nome_fantasia",
      label: "Nome da Empresa:",
      type: "text",
      name: "nome_fantasia",
      required: true,
    },
    {
      id: "cnpj",
      label: "CNPJ:",
      type: "text",
      name: "cnpj",
      required: true,
    },
    {
      id: "email",
      label: "Email Corporativo:",
      type: "email",
      name: "email",
      required: true,
    },
    {
      id: "telefone",
      label: "Telefone Corporativo:",
      type: "tel",
      name: "telefone",
      required: false,
    },
    {
      id: "endereco",
      label: "Endereço:",
      type: "text",
      name: "endereco",
      required: false,
    },
    {
      id: "razao_social",
      label: "Razão Social:",
      type: "text",
      name: "razao_social",
      required: false,
    },
  ],
  usuarios: [
    {
      id: "nome",
      label: "Nome:",
      type: "text",
      name: "nome",
      required: true,
    },
    {
      id: "usuario",
      label: "Usuario:",
      type: "text",
      name: "usuario",
      required: true,
    },
    {
      id: "email",
      label: "Email:",
      type: "email",
      name: "email",
      required: true,
    },
    {
      id: "senha",
      label: "Senha:",
      type: "password",
      name: "senha",
      required: true,
    },
    {
      id: "telefone",
      label: "Telefone:",
      type: "tel",
      name: "telefone",
      required: false,
    },
  ],

  colaboradores: [
    {
      id: "nome",
      label: "Nome:",
      type: "text",
      name: "nome",
      required: true,
    },
    {
      id: "cpf",
      label: "CPF:",
      type: "text",
      name: "cpf",
      required: true,
    },
    {
      id: "endereco",
      label: "Endereço:",
      type: "text",
      name: "endereco",
      required: true,
    },
    {
      id: "telefone",
      label: "Telefone:",
      type: "tel",
      name: "telefone",
      required: false,
    },
    {
      id: "email",
      label: "Email:",
      type: "email",
      name: "email",
      required: true,
    },
    {
      id: "anotacoes",
      label: "Anotações:",
      type: "text",
      name: "anotacoes",
      required: false,
    },
  ],
  animais: [
    {
      id: "data_entrada",
      label: "Data de Entrada:",
      type: "date",
      name: "data_entrada",
      required: true,
    },
    {
      id: "especie",
      label: "Especie",
      type: "text",
      name: "especie",
      required: false,
    },
    {
      id: "apelido",
      label: "Apelido:",
      type: "text",
      name: "apelido",
      required: false,
    },

    {
      id: "raca",
      label: "Raça:",
      type: "text",
      name: "raca",
      required: false,
    },
    {
      id: "porte",
      label: "Porte:",
      type: "text",
      name: "porte",
      required: false,
    },
    {
      id: "cor",
      label: "Cor:",
      type: "text",
      name: "cor",
      required: false,
    },
    {
      id: "peso",
      label: "Peso:",
      type: "text",
      name: "peso",
      required: false,
    },
    {
      id: "anotacoes",
      label: "Anotações:",
      type: "text",
      name: "anotacoes",
      required: false,
    },
    {
      id: "adotado",
      label: "Foi adotado?",
      type: "select",
      name: "adotado",
      options: [
        { value: "yes", label: "Sim" },
        { value: "no", label: "Não" },
      ],
      required: true,
    },
    {
      id: "data_adocao",
      label: "Data de Adoção:",
      type: "date",
      name: "data_adocao",
      required: false,
      condition: { field: "adotado", value: "yes" },
    },
    {
      id: "tutor_id",
      label: "Tutor:",
      type: "select_api",
      name: "tutor_id",
      required: false,
      condition: { field: "adotado", value: "yes" },
      apiSource: "tutores",
      valueField: "id",
      labelField: "nome",
      labelFields: "nome",
    },
  ],
  interessados: [
    {
      id: "nome",
      label: "Nome:",
      type: "text",
      name: "nome",
      required: true,
    },
    {
      id: "endereco",
      label: "Endereço:",
      type: "text",
      name: "endereco",
      required: false,
    },
    {
      id: "telefone",
      label: "Telefone:",
      type: "tel",
      name: "telefone",
      required: false,
    },
    {
      id: "email",
      label: "E-mail:",
      type: "email",
      name: "email",
      required: false,
    },
    {
      id: "rede_social",
      label: "Rede social:",
      type: "text",
      name: "rede_social",
      required: false,
    },
    {
      id: "anotacoes",
      label: "Anotações:",
      type: "text",
      name: "anotacoes",
      required: false,
    },
  ],
  tutores: [
    {
      id: "nome",
      label: "Nome:",
      type: "text",
      name: "nome",
      required: true,
    },
    {
      id: "cpf",
      label: "CPF:",
      type: "text",
      name: "cpf",
      required: true,
    },
    {
      id: "endereco",
      label: "Endereço:",
      type: "text",
      name: "endereco",
      required: false,
    },
    {
      id: "telefone",
      label: "Telefone:",
      type: "tel",
      name: "telefone",
      required: false,
    },
    {
      id: "email",
      label: "E-mail:",
      type: "email",
      name: "email",
      required: false,
    },
    {
      id: "anotacoes",
      label: "Anotações:",
      type: "text",
      name: "anotacoes",
      required: false,
    },
  ],
  agendamentos: [
    {
      id: "procedimento",
      label: "Castração / Vacinação:",
      type: "select",
      name: "procedimento",
      options: [
        { value: "CASTRACAO", label: "Castração" },
        { value: "VACINACAO", label: "Vacinação" },
      ],
      required: true,
    },
    {
      id: "data",
      label: "Data:",
      type: "date",
      name: "data",
      required: true,
    },
    {
      id: "animal_id",
      label: "Animal",
      type: "text",
      name: "animal_id",
      required: true,
      nested: true,
      path: "animal.id",
    },
    {
      id: "colaborador_id",
      label: "Colaborador",
      type: "text",
      name: "colaborador_id",
      required: false,
      nested: true,
      path: "colaborador.id",
    },
    {
      id: "telefone_colaborador",
      label: "Fone Colaborador:",
      type: "tel",
      name: "telefone_colaborador",
      required: false,
      nested: true,
      path: "colaborador.telefone",
    },
    {
      id: "tutor_id",
      label: "Tutor",
      type: "text",
      name: "tutor_id",
      required: false,
      nested: true,
      path: "tutor.id",
    },
    {
      id: "telefone_tutor",
      label: "Fone Tutor:",
      type: "tel",
      name: "telefone_tutor",
      required: false,
      nested: true,
      path: "tutor.telefone",
    },
    // {
      // id: "tutor_nome",
      // label: "Nome do Tutor:",
      // type: "text",
      // name: "tutor_nome",
      // required: false,
      // nested: true,
      // path: "tutor.nome",
    // },
  ],
};
